name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update branch
        run: |
          git fetch --all
          git checkout main
          git pull origin main

      - name: Release extension on GitHub
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        shell: bash
        run: |
          DATE=$(grep "^date-released:" CITATION.cff | sed 's/date-released: //;s/"//g')
          VERSION=$(grep "^version:" CITATION.cff | sed 's/version: //;s/"//g')
          gh release create ${VERSION} --title ${DATE} --generate-notes
